trigger:
  branches:
    include:
      - main

# 👇 Ye self-hosted agent pool ka naam hai
pool:
  name: 'Test'

stages:
- stage: Test
  displayName: "Run Cypress Tests"
  jobs:
    - job: TestJob
      steps:
        - task: NodeTool@0
          inputs:
            versionSpec: '18.x'
          displayName: "Install Node.js"

        - script: |
            npm ci
            npx cypress install
            npx cypress run --browser electron --headless --spec "cypress/e2e/integration/*.cy.js"
          displayName: "Execute Cypress Tests"

- stage: Build
  dependsOn: Test
  displayName: "Build Project"
  jobs:
    - job: BuildJob
      steps:
        - script: npm run build
          displayName: "Build Project"

- stage: Release
  dependsOn: Build
  displayName: "Deploy to Staging/Production"
  jobs:
    - job: ReleaseJob
      steps:
        - script: echo "Deploying application..."
          displayName: "Release Stage"