trigger:
  branches:
    include:
      - main

# 👇 Self-hosted agent pool
pool:
  name: 'Test'

stages:
# ========================
# 🧪 Run Cypress Tests
# ========================
- stage: Test
  displayName: "Run Cypress Tests"
  jobs:
    - job: TestJob
      steps:
        # ✅ Install Node.js (compatible version)
        - task: NodeTool@0
          inputs:
            versionSpec: '18.18.2'
          displayName: "Install Node.js 18.18.2"

        # ✅ Run Cypress Tests
        - script: |
            echo "Installing dependencies..."
            npm ci
            echo "Verifying Cypress installation..."
            npx cypress verify
            echo "Running Cypress tests..."
            npx cypress run --browser electron --headless --spec "cypress/e2e/integration/*.cy.js"
          displayName: "Execute Cypress Tests"
